[package]
name = "mrs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["now"] }
color-eyre = "0.6"
crossterm = "0.29"
csv = "1.3"
dirs = "6.0.0"
ratatui = "0.29"
serde = { version = "1", features = ["derive"]}
